import { describe, expect, it } from "vitest";
import {
  encodeGeohash,
  geohashBounds,
  geohashNeighbours,
  geohashesInBounds,
  TILE_PRECISION,
} from "../src/geo/geohash.js";
import vectors from "./fixtures/geohash-vectors.json" with { type: "json" };

/**
 * These vectors are generated by packages/pipeline/geohash.py. Tile keys cross
 * the pipeline/runtime boundary, so the two implementations must agree exactly
 * — a disagreement means the runtime requests tiles the pipeline never wrote,
 * which shows up as silently unreachable roads rather than an error.
 *
 * Regenerate with:
 *   cd packages/pipeline && ./.venv/Scripts/python.exe -c "..."  (see README)
 */
describe("geohash cross-language agreement", () => {
  it("matches the Python encoder on every vector", () => {
    for (const { lat, lon, hash } of vectors.encode) {
      expect(encodeGeohash(lat, lon, TILE_PRECISION), `${lat},${lon}`).toBe(hash);
    }
  });

  it("matches the Python bounds implementation", () => {
    for (const { hash, bounds } of vectors.bounds) {
      const [minLat, minLon, maxLat, maxLon] = bounds as [number, number, number, number];
      const got = geohashBounds(hash);
      expect(got.minLat, `${hash} minLat`).toBeCloseTo(minLat, 10);
      expect(got.minLon, `${hash} minLon`).toBeCloseTo(minLon, 10);
      expect(got.maxLat, `${hash} maxLat`).toBeCloseTo(maxLat, 10);
      expect(got.maxLon, `${hash} maxLon`).toBeCloseTo(maxLon, 10);
    }
  });

  it("matches the Python neighbour derivation", () => {
    for (const { hash, neighbours } of vectors.neighbours) {
      expect(geohashNeighbours(hash), hash).toEqual(neighbours);
    }
  });
});

describe("encodeGeohash", () => {
  it("reproduces the canonical reference vector", () => {
    expect(encodeGeohash(57.64911, 10.40744, 6)).toBe("u4pruy");
  });

  it("honours the requested precision", () => {
    for (let precision = 1; precision <= 9; precision++) {
      expect(encodeGeohash(28.6315, 77.2167, precision)).toHaveLength(precision);
    }
  });

  it("produces prefix-nested hashes as precision grows", () => {
    // A defining geohash property: lower precision is a prefix of higher, so
    // string prefix matching is a spatial containment test.
    const fine = encodeGeohash(28.6315, 77.2167, 9);
    for (let precision = 1; precision < 9; precision++) {
      expect(fine.startsWith(encodeGeohash(28.6315, 77.2167, precision))).toBe(true);
    }
  });

  it("handles the coordinate extremes", () => {
    expect(encodeGeohash(-90, -180, 6)).toBe("000000");
    expect(encodeGeohash(90, 180, 6)).toBe("zzzzzz");
  });
});

describe("geohashBounds", () => {
  it("returns a box containing the point that produced the hash", () => {
    const lat = 28.6315;
    const lon = 77.2167;
    const { minLat, minLon, maxLat, maxLon } = geohashBounds(encodeGeohash(lat, lon));

    expect(lat).toBeGreaterThanOrEqual(minLat);
    expect(lat).toBeLessThanOrEqual(maxLat);
    expect(lon).toBeGreaterThanOrEqual(minLon);
    expect(lon).toBeLessThanOrEqual(maxLon);
  });

  it("gives precision-6 cells of roughly 1.22km x 0.61km", () => {
    // The size the tiling scheme is designed around; a change here would blow
    // the ~7KB-per-tile and ~2000-tiles-for-Delhi budget.
    const { minLat, minLon, maxLat, maxLon } = geohashBounds(encodeGeohash(28.6315, 77.2167));
    const heightKm = (maxLat - minLat) * 111.32;
    const widthKm = (maxLon - minLon) * 111.32 * Math.cos((28.6315 * Math.PI) / 180);

    expect(heightKm).toBeGreaterThan(0.5);
    expect(heightKm).toBeLessThan(0.7);
    expect(widthKm).toBeGreaterThan(0.9);
    expect(widthKm).toBeLessThan(1.3);
  });

  it("rejects characters outside the geohash alphabet", () => {
    // 'a', 'i', 'l', 'o' are excluded to avoid visual confusion.
    expect(() => geohashBounds("ttnfva")).toThrow(/invalid geohash character/);
    expect(() => geohashBounds("ttnfvi")).toThrow(/invalid geohash character/);
  });
});

describe("geohashNeighbours", () => {
  it("returns eight distinct cells, none of them the input", () => {
    const neighbours = geohashNeighbours("ttnfvh");
    expect(neighbours).toHaveLength(8);
    expect(new Set(neighbours).size).toBe(8);
    expect(neighbours).not.toContain("ttnfvh");
  });

  it("returns cells adjacent to the input cell", () => {
    const centre = geohashBounds("ttnfvh");
    const latSpan = centre.maxLat - centre.minLat;
    const lonSpan = centre.maxLon - centre.minLon;

    for (const neighbour of geohashNeighbours("ttnfvh")) {
      const box = geohashBounds(neighbour);
      // Every neighbour centre sits within ~1.5 cells of the origin centre.
      const dLat = Math.abs((box.minLat + box.maxLat) / 2 - (centre.minLat + centre.maxLat) / 2);
      const dLon = Math.abs((box.minLon + box.maxLon) / 2 - (centre.minLon + centre.maxLon) / 2);
      expect(dLat).toBeLessThanOrEqual(latSpan * 1.5);
      expect(dLon).toBeLessThanOrEqual(lonSpan * 1.5);
    }
  });
});

describe("geohashesInBounds", () => {
  it("covers a small box with the cell containing it", () => {
    const hash = encodeGeohash(28.6315, 77.2167);
    const box = geohashBounds(hash);
    // Query strictly inside one cell.
    const inset = {
      minLat: box.minLat + (box.maxLat - box.minLat) * 0.4,
      minLon: box.minLon + (box.maxLon - box.minLon) * 0.4,
      maxLat: box.maxLat - (box.maxLat - box.minLat) * 0.4,
      maxLon: box.maxLon - (box.maxLon - box.minLon) * 0.4,
    };
    expect(geohashesInBounds(inset)).toContain(hash);
  });

  it("covers every corner of a multi-cell box", () => {
    // Connaught Place to India Gate — the demo route's corridor.
    const bounds = { minLat: 28.6129, minLon: 77.2167, maxLat: 28.6315, maxLon: 77.2295 };
    const cells = geohashesInBounds(bounds);

    for (const [lat, lon] of [
      [bounds.minLat, bounds.minLon],
      [bounds.minLat, bounds.maxLon],
      [bounds.maxLat, bounds.minLon],
      [bounds.maxLat, bounds.maxLon],
    ] as const) {
      expect(cells, `corner ${lat},${lon}`).toContain(encodeGeohash(lat, lon));
    }
  });

  it("returns a tile count proportional to the area covered", () => {
    const small = geohashesInBounds({
      minLat: 28.61,
      minLon: 77.21,
      maxLat: 28.62,
      maxLon: 77.22,
    });
    const large = geohashesInBounds({
      minLat: 28.55,
      minLon: 77.15,
      maxLat: 28.70,
      maxLon: 77.30,
    });
    expect(large.length).toBeGreaterThan(small.length);
    // Sanity bound: the wider box is ~15km x 15km, roughly 12x25 cells.
    expect(large.length).toBeLessThan(1000);
  });
});
